package com.example.accessingdatamysql.service;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.example.accessingdatamysql.model.Student;
import com.example.accessingdatamysql.service.repo.StudentRepository;
import com.example.accessingdatamysql.service.repo.entity.StudentEntity;

@Service    
public class StudentService {

	@Autowired // This means to get the bean called userRepository which is auto-generated by Spring, we will use it to handle the data
	private StudentRepository studentRepository;

    

    public List<Student> findAll() {   
        Iterable<StudentEntity> iter = studentRepository.findAll();
        
        
        List<Student> ls = new ArrayList<>();    
        iter.forEach(studentEntity -> {
            Student student = new Student();
            student.setId(studentEntity.getId());
            student.setName(studentEntity.getName());
            student.setEmail(studentEntity.getEmail());
            student.setIsActive(1 == studentEntity.getState());
            ls.add(student);
        });    
        return ls;    
    }


    public Student save(Student s) {

        StudentEntity e = new StudentEntity();
        e.setName(s.getName());
        e.setEmail(s.getEmail());
        e.setState(1);
        e.setCreated(new Timestamp(System.currentTimeMillis()));

        StudentEntity resulStudentEntity = studentRepository.save(e);

        Student resulStudent = new Student();
        resulStudent.setId(resulStudentEntity.getId());
        resulStudent.setName(resulStudentEntity.getName());
        resulStudent.setEmail(resulStudentEntity.getEmail());
        resulStudent.setIsActive(1==e.getState());
        return resulStudent;
    }
}
